; Hyggshi Configuration Language (HCL)

; only update system

;==========Start of base==========
[my-version-os-base]
Version = 1.4.1
name = "Hyggshi OS ${Version} ${codename} Debian Edition"
codename = "Verdant Valley"
;==========END OF BASE==========


;==========Start of OTA==========
[ota]

enabled = true
channel = "stable"

metadata-url = "https://raw.githubusercontent.com/Hyggshi-OS-Research-Technology/Hyggshi-OS-Releases/main/hyggshi-os-ota/metadata/stable.json"

update-system = true
update-apps = false

preserve-home = true
preserve-user-data = true

check-disk-space = true
check-network = true
check-power = true

require-confirmation = true
auto-reboot = false

rollback-enabled = true
log-file = "/var/log/hyggshi-ota.log"

;==========END OF OTA==========


;==========Start of package==========
[package]

;==========
; compilers and tools
;==========
python = true
jq = true
wget = true
curl = true

;==========
; App Hyggshi OS Ecosystem
;==========
nexcode-install-web = install-web(
run = "wget https://github.com/Hyggshi-OS-project-center/NexCode/releases/download/v4.0.2/nexcode-ide-4.0.2-amd64.deb"
run = "sudo apt install -y ./nexcode-ide-4.0.2-amd64.deb"
)

;==========
; install flatpak and flathub
;==========
flatpak1 = command(
run = "sudo ln -s /proc/mounts /etc/mtab"
)

flatpak2 = command(
run = "sudo rm -rf /var/tmp/flatpak-cache-*"
)

;==========Remove package and image==========
image-background = command(
download = "https://raw.githubusercontent.com/Hyggshi-OS-Research-Technology/Hyggshi-OS/38c4c3d47efca20f7872467f933c40820c331a4d/iso-config/branding/xfce-x.svg"
run = "cp -f ~/Downloads/xfce-x.svg /usr/share/backgrounds/xfce/xfce-x.svg"
)

;==========END OF REMOVE PACKAGE AND IMAGE==========


;==========Start of customization==========
[customization]

;==========
; customization for LightDM Greeter GTK theme
;==========
greeter-gtk-theme = copy(
source = "./resources/gtk.css"
rename = "gtk.css"
target = "/usr/share/themes/Hyggshi-Greeter/gtk-3.0/"
)

;==========END OF CUSTOMIZATION==========


;==========Start of compilers==========
[compilers]

; Build và cài đặt Hyggshi Sound Shortcut
linkhyggshi-sound-shortcut = command(
file = "./resources/hyggshi-extensions-sound-shortcut/sound-shortcut.sh"
action = run
)

linkhyggshi-welcome = command(
file = "./resources/hyggshi-extensions-welcome/welcome.sh"
action = run
)

;==========END OF COMPILERS==========